import { Language } from '../types';

export const translations = {
  it: {
    nav: {
      title: "SmartCompound",
      github: "GitHub Repo",
      star: "Star on GitHub",
      tools: {
        calculator: "Calcolatrice",
        chart: "Grafico",
        ai: "AI Mentor"
      }
    },
    hero: {
      titleStart: "Trasforma il tuo ",
      titleHighlight1: "Caffè",
      titleMiddle: " in un ",
      titleHighlight2: "Impero",
      titleEnd: ".",
      subtitle: "Scopri come investire pochi euro al giorno per un breve periodo può garantirti un capitale enorme in futuro grazie alla magia dell'interesse composto."
    },
    config: {
      title: "Configura il tuo Piano",
      strategy: "Strategia",
      strategies: {
        optimal: "Smart (18-23 anni)",
        late: "Tradizionale (25-65)",
        custom: "Personalizzata"
      },
      dailyLabel: "Risparmio Giornaliero",
      monthlyLabel: "mese",
      dailyNoteLow: "Il costo di una colazione al bar.",
      dailyNoteHigh: "Meno di un aperitivo a settimana.",
      rateLabel: "Rendimento Annuo",
      rateNote: "Storico S&P 500 (aggiustato inflazione): ~7-10%",
      startAgeLabel: "Età di Inizio",
      durationLabel: "Anni di Versamento",
      targetAgeLabel: "Età Target",
      summary: (start: number, end: number, years: number) => 
        `Versi soldi dai ${start} ai ${end} anni. Poi lasci che il mercato lavori per te per ${years} anni.`
    },
    stats: {
      invested: "Tu versi solo",
      market: "Il mercato regala",
      total: "Capitale a",
      multiplier: "Moltiplicatore"
    },
    chart: {
      title: "Proiezione della Crescita",
      axisAge: "Età",
      tooltipAge: "Età",
      seriesValue: "Valore Totale",
      seriesPrincipal: "Soldi Versati",
      seriesInterest: "Interessi",
      roi: "Rendimento Totale",
      labelStopContrib: "Stop Versamenti"
    },
    advisor: {
      title: "L'Opinione dell'AI",
      subtitle: "Analisi personalizzata basata sui tuoi dati",
      buttonIdle: "Genera Analisi",
      buttonLoading: "Analizzo...",
      disclaimer: "Generato da Gemini 2.5 Flash • Potrebbe contenere errori",
      placeholderTitle: "Vuoi sapere se questa strategia ha senso per te?",
      placeholderText: "Chiedi all'intelligenza artificiale di analizzare il tuo piano.",
      errorKey: "API Key non configurata.",
      errorGen: "Errore durante la generazione."
    },
    footer: {
      text: "SmartCompound è un progetto open source per l'educazione finanziaria.",
      disclaimer: "I calcoli sono simulazioni e non costituiscono consulenza finanziaria."
    }
  },
  en: {
    nav: {
      title: "SmartCompound",
      github: "GitHub Repo",
      star: "Star on GitHub",
      tools: {
        calculator: "Calculator",
        chart: "Chart",
        ai: "AI Mentor"
      }
    },
    hero: {
      titleStart: "Turn your ",
      titleHighlight1: "Coffee",
      titleMiddle: " into an ",
      titleHighlight2: "Empire",
      titleEnd: ".",
      subtitle: "Discover how investing just a few dollars a day for a short period can guarantee a huge capital in the future thanks to the magic of compound interest."
    },
    config: {
      title: "Configure Your Plan",
      strategy: "Strategy",
      strategies: {
        optimal: "Smart (18-23y)",
        late: "Traditional (25-65)",
        custom: "Custom"
      },
      dailyLabel: "Daily Savings",
      monthlyLabel: "mo",
      dailyNoteLow: "About the cost of a coffee.",
      dailyNoteHigh: "Less than a drink per week.",
      rateLabel: "Annual Return",
      rateNote: "S&P 500 Historical (inflation adj): ~7-10%",
      startAgeLabel: "Start Age",
      durationLabel: "Years of Contribution",
      targetAgeLabel: "Target Age",
      summary: (start: number, end: number, years: number) => 
        `You contribute from age ${start} to ${end}. Then allow the market to work for you for ${years} years.`
    },
    stats: {
      invested: "You only pay",
      market: "Market gives",
      total: "Capital at age",
      multiplier: "Multiplier"
    },
    chart: {
      title: "Growth Projection",
      axisAge: "Age",
      tooltipAge: "Age",
      seriesValue: "Total Value",
      seriesPrincipal: "Cash Invested",
      seriesInterest: "Interest Earned",
      roi: "Total ROI",
      labelStopContrib: "Stop Contrib."
    },
    advisor: {
      title: "AI Financial Mentor",
      subtitle: "Personalized analysis based on your data",
      buttonIdle: "Get AI Opinion",
      buttonLoading: "Analyzing...",
      disclaimer: "Generated by Gemini 2.5 Flash • May contain errors",
      placeholderTitle: "Does this strategy make sense for you?",
      placeholderText: "Ask Artificial Intelligence to analyze your plan.",
      errorKey: "API Key not configured.",
      errorGen: "Error generating analysis."
    },
    footer: {
      text: "SmartCompound is an open source project for financial literacy.",
      disclaimer: "Calculations are simulations and do not constitute financial advice."
    }
  }
};